Updated scritps for bench

diff --git a/samples/deployment/test-network/Makefile b/samples/deployment/test-network/Makefile
--- a/samples/deployment/test-network/Makefile
+++ b/samples/deployment/test-network/Makefile
@@ -38,5 +38,17 @@ ercc-ecc-start:
 	fi && \
 	env CC_ID=${CC_ID} FPC_VERSION=${FPC_VERSION} docker-compose up
 
+ercc-ecc-background:
+	if [ ! -z "${DOCKERD_FPC_PATH}" ]; then \
+  		export SGX_CREDENTIALS_PATH="${DOCKERD_FPC_PATH}/integration/config/ias"; \
+  	fi && \
+	if [ "${SGX_MODE}" = "HW" ]; then \
+		export HW_EXTENSION="-hw" \
+		    AESMD_PATH="/var/run/aesmd" \
+		    SGX_DEVICE_PATH=$$(if [ -e "/dev/isgx" ]; then echo "/dev/isgx"; elif [ -e "/dev/sgx/enclave" ]; then echo "/dev/sgx/enclave"; else echo "none"; fi) && \
+		[ "$${SGX_DEVICE_PATH}" != "none" ] || ( echo "ERROR: SGX_MODE is HW but no sgx device found"; exit 1; ) \
+	fi && \
+	env CC_ID=${CC_ID} FPC_VERSION=${FPC_VERSION} docker-compose up -d
+
 ercc-ecc-stop:
 	env CC_ID=${CC_ID} FPC_VERSION=${FPC_VERSION} docker-compose down
